version: "2.4"

services:
  youyaku_ai_db:
    image: youyaku_ai_db
    build:
      context: ./docker/db/
      dockerfile: ./Dockerfile
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
  youyaku_ai_dashboard:
    image: youyaku_ai_dashboard
    build:
      context: ./docker/dashboard
      dockerfile: ./Dockerfile
    container_name: youyaku_ai_dashboard
    volumes:
      - ./src/dashboard:/workspace/dashboard
      - ./src/db:/workspace/db
      - ./src/log:/workspace/log
      - ./credentials:/workspace/credentials
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TYPE: ${DB_TYPE}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_SERVICE_ACCOUNT_FILE}
    tty: true
    ports:
      - "8501:8501" # for streamlit or plotly dash
    depends_on:
      - youyaku_ai_db
      - youyaku_ai_api_gateway
    entrypoint: "python3 dashboard/app.py"
  youyaku_ai_api_gateway:
    image: youyaku_ai_api_gateway
    build:
      context: ./docker/api_gateway
      dockerfile: ./Dockerfile
    container_name: youyaku_ai_api_gateway
    volumes:
      - ./src/api_gateway:/workspace/api_gateway
      - ./src/queue_api:/workspace/queue_api
      - ./src/db:/workspace/db
      - ./src/log:/workspace/log
      - ./credentials:/workspace/credentials
    ports:
      - "${API_PORT}:${API_PORT}"
    tty: true
    environment:
      QUEUE_HOST: ${QUEUE_HOST}
      QUEUE_PORT: ${QUEUE_PORT}
      QUEUE_NAME: ${QUEUE_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TYPE: ${DB_TYPE}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_SERVICE_ACCOUNT_FILE}
    depends_on:
      - youyaku_ai_db
      - youyaku_ai_queue_broker
      - youyaku_ai_summarizer_processor
    entrypoint: "uvicorn api_gateway.main:app --reload --host 0.0.0.0 --port ${API_PORT}"
  youyaku_ai_summarizer:
    image: youyaku_ai_summarizer
    build:
      context: ./docker/summarizer
      dockerfile: ./Dockerfile
      target: local
    container_name: youyaku_ai_summarizer
    volumes:
      - ./src/log:/workspace/log
      - ./src/summarizer:/workspace/summarizer
      - ./model:/workspace/summarizer/model
    environment:
      SUMMARIZER_INTERNAL_API_LOCAL_PORT: ${SUMMARIZER_INTERNAL_API_LOCAL_PORT}
    ports:
      - "${SUMMARIZER_INTERNAL_API_LOCAL_PORT}:${SUMMARIZER_INTERNAL_API_LOCAL_\
        PORT}"
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "python summarizer/health_check.py" ]
      start_period: "10s"
      retries: 10
      timeout: "10s"
      interval: "10s"
    entrypoint: "uvicorn summarizer.serve:app --reload --host 0.0.0.0 --port
      ${SUMMARIZER_INTERNAL_API_LOCAL_PORT}"
  youyaku_ai_summarizer_processor:
    image: youyaku_ai_summarizer_processor
    build:
      context: ./docker/summarizer_processor
      dockerfile: ./Dockerfile
      target: local
    container_name: youyaku_ai_summarizer_processor
    volumes:
      - ./src/queue_api:/workspace/queue_api
      - ./src/db:/workspace/db
      - ./src/log:/workspace/log
      - ./src/summarizer_processor:/workspace/summarizer_processor
      - ./credentials:/workspace/credentials
    tty: true
    environment:
      QUEUE_HOST: ${QUEUE_HOST}
      QUEUE_PORT: ${QUEUE_PORT}
      QUEUE_NAME: ${QUEUE_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TYPE: ${DB_TYPE}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_SERVICE_ACCOUNT_FILE}
      SUMMARIZER_INTERNAL_API_LOCAL_HOST: ${SUMMARIZER_INTERNAL_API_LOCAL_HOST}
      SUMMARIZER_INTERNAL_API_LOCAL_PORT: ${SUMMARIZER_INTERNAL_API_LOCAL_PORT}
      SUMMARIZER_INTERNAL_API_TYPE: ${SUMMARIZER_INTERNAL_API_TYPE}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_PREDICTION_LOCATION: ${GOOGLE_PREDICTION_LOCATION}
      GOOGLE_PREDICTION_ENDPOINT: ${GOOGLE_PREDICTION_ENDPOINT}
    depends_on:
      youyaku_ai_db:
        condition: service_started
      youyaku_ai_queue_broker:
        condition: service_started
      youyaku_ai_summarizer:
        condition: service_healthy
    entrypoint: "python3 summarizer_processor/summarizer_process.py"
  youyaku_ai_queue_zookeeper:
    image: bitnami/zookeeper:latest
    container_name: youyaku_ai_queue_zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  youyaku_ai_queue_broker:
    image: 'bitnami/kafka:latest'
    container_name: ${QUEUE_HOST}
    ports:
      - "${QUEUE_PORT}:${QUEUE_PORT}" # for internal container
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=youyaku_ai_queue_zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:${QUEUE_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://${QUEUE_HOST}:${QUEUE_PORT}
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - youyaku_ai_queue_zookeeper
